# ✅ Workflow name
name: CI/CD HTML Portfolio to Netlify (Windows)

# ✅ Trigger on push to main
on:
  push:
    branches:
      - main  # 👉 Change this to 'master' or your branch name if different

jobs:
  deploy:
    runs-on: windows-latest  # ✅ Using Windows runner

    steps:
      # ✅ Step 1: Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Step 2: Deploy the static HTML site to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: .\\  # 👉 Deploy from root directory (Windows uses \\)
          production-deploy: true
          NETLIFY_AUTH_TOKEN: ${{ nfp_purGU6ZWzWyXTETLV6bNEGRKnGbJiybh0dda }}
          NETLIFY_SITE_ID: ${{ f2601a9f-812a-4472-9d99-e95e6af5372b }}
